## Climbing sale

Will run the webscrapes, gather and filter the ideal items, presenting what we want

#### Getting Firefox, gecko and selenium to work :)

This was genuinely remarkable difficult, so here is how i did it (inside a jupyter lab instance through ubuntu). All the following commands are ran in a terminal inside the lab instance (no kernel)

First install firefox, latest version as from this [website vi apt (not snap!)](https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04)

```

    https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04

    follow this
```

Now we need to install the latest geckodriver for firefox, these are helpful [stack](https://stackoverflow.com/questions/40867959/installing-geckodriver-only-using-terminal). Note that i had to put the driver in `/usr/bin` not `/usr/local/bin`

```

    328: wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
    329  sudo mv geckodriver-v0.36.0-linux64.tar.gz /usr/bin
    330  cd /usr/bin
    331  sudo tar -xvf geckodriver-v0.36.0-linux64.tar.gz 
    332  sudo chmod +x geckodriver
    333  geckodriver
```

Finally migrate to the kernel/virtualenv you want, and install selenium:

```
pip install -U selenium
```

In [1]:
from climbing_scraper import scraper
import warnings
warnings.filterwarnings("ignore")

In [5]:
out = scraper.scrape()
scraper.display(out, 500)